### ISSUE TITLE
only seeing white screen

### ISSUE THREAD

**Issue by gilgo** [PokemonGoF/PokemonGo-Web#11]
bots just went online, tried to make it work but only seeing a white screen...
(cleared history and cookies)

**Comment by JaroSound** [comment]
Same here.

**Comment by gilgo** [comment]
sry it works fine im just stupid, forgot i installed a fresh copy and so my configs were wiped...

go to your config folder and edit the lines there, if u wanna show multiple bots the correct syntax is :
users: ["1st user","2nd user"],

**Comment by ProjectBarks** [comment]
Also make sure you have attached a google maps API key. look inside of the root folder **config/userdata.js.example** and then rename it to **config/userdata.js** after changing the variables.
