### ISSUE TITLE
New socket.io.js source

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Web#111]
Hi
It seems that https://cdn.socket.io/socket.io-1.4.5.js is not longer available. 
According to socket.io website, the new address is:
https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.js 

Posting this here, because it seems that PR takes some time to be merged... :)

**Comment by solderzzc** [comment]
@pogarek I think you also can merge submit on this repo?

**Comment by pogarek** [comment]
@solderzzc I'll try to do PR and merge here shortly. Previously I couldn't

**Comment by solderzzc** [comment]
@pogarek  Yes, I just checked the project setting and added you to the web team.

**Comment by pogarek** [comment]
I do confirm - was able to merge. Thanks a lot :)  
Now it is a time to PR for bot - regarding webui commit and broker.pikabot.org issue ;) 
Closing this issue.

**Comment by solderzzc** [comment]
Sigh, it's a little bit expensive for running a broker.... So I didn't pay the renew fee...

**Comment by pogarek** [comment]
understood :-) it is disabled now, PR is done and under testing :) 
btw: check your PM on discord :)

**Comment by solderzzc** [comment]
OK, I'll find a new server for it.

**Comment by pogarek** [comment]
thanks.

**Comment by solderzzc** [comment]
Have it done :) broker is running.

**Comment by pogarek** [comment]
:-) LOL. :-) I'll do another commit then - CI tests failed :(

**Comment by solderzzc** [comment]
![screen shot 2017-03-01 at 12 45 51 pm](https://cloud.githubusercontent.com/assets/3085564/23480510/07ba66b4-fe7d-11e6-811c-641eb455149b.png)
