### ISSUE TITLE
Shiny pokemons - which ones

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Web#117]
Since we bot is able to catch Shiny's pokemon, it would be good if webui would show which Pokemon is shiny, which one is not. 

@Jcolomar  - is this for you ?

**Comment by Jcolomar** [comment]
i was thinking about it. I have to understand how to implement it

**Comment by Jcolomar** [comment]
by the moment i cannot find a solution to add shiny pokemons to web

**Comment by pogarek** [comment]
Is someoene will find a shiny pokemon in inventory-xxx.json file  in : 
```
"inventory_item_data": {
            "pokemon_data": {
```
then please paste the record here.

**Comment by Jcolomar** [comment]
https://github.com/PokemonGoF/PokemonGo-Web/pull/131

**Comment by goedzo** [comment]
Implemented!
