### ISSUE TITLE
Help Wanted with multiple bots in one Web UI

### ISSUE THREAD

**Issue by ghost** [PokemonGoF/PokemonGo-Web#118]
I have 2 Bots running on 2 Servers

What I want to do is to have both bots showing in the Web UI of Server1
What is working in this config is that both accounts are shown on the right under "bots",
but only account1@gmail.com is showing a route and any informations about Info or Pokemon.
The Log Popups in the bottom left show information from both bots.

I opened ports 4000 and 5000

The webserver is nginx, but with the python webserver it did exactly the same.
I changed the Web UI to port 80 far before i added the second bot.

The Userdata.js on the Server1 with the active Web UI

>  users: [{
            enable: true,
            username: "account1@gmail.com",
            socketAddress: "externalIP-Server1:4000",
            enableSocket: true
        },{
            enable: true,
            username: "account2@gmail.com",
            socketAddress: "externalIP-Server2:5000",
            enableSocket: true

Config on Server1

> {
    "websocket_server": true,
   ...
  "websocket": {
        "start_embedded_server": true,
        "server_url": "externalIP-Server1:4000"
    }
}

Config on Server2

> {
    "websocket_server": true,
...
   "websocket": {
        "start_embedded_server": true,
        "server_url": "externalIP-Server2:5000"
    }
}

Can anybody help me?
I cant find a full documetation about running multiple bots in one Web UI, is there one?

**Comment by goedzo** [comment]
Old issue, multiple accounts are working fine in bot.
