### ISSUE TITLE
Socket.io error 404

### ISSUE THREAD

**Issue by rafzx2** [PokemonGoF/PokemonGo-Web#18]
Bot avatar freeze on start position;

Using: Ubuntu Server 16 LTS
WebServer : Python Simple HTTP

![image](https://cloud.githubusercontent.com/assets/20955456/17595368/2e968fc8-5fc3-11e6-9305-fe6ce59cc136.png)

**Comment by Jasperrr91** [comment]
To display the logs, the master branch automatically tries to connect to a socket.io at port 8000. Which probably isn't running on your computer. This is a feature that should have been made optional in the userdata config file but sadly, it hasn't been. You can either ignore this or enable websockets in your bot's config.

**Comment by Jasperrr91** [comment]
Ah, use this web ui instead: https://github.com/OpenPoGo/OpenPoGoWeb. Or wait till the rewrite branch is done.
