### ISSUE TITLE
Actions don't seem to be working

### ISSUE THREAD

**Issue by Lntnam** [PokemonGoF/PokemonGo-Web#24]
I tried to release some pokemons from the UI but it doesn't seem to be working.

**Comment by oralunal** [comment]
Actions are on PoGoBotWeb not on this repo.

**Comment by Lntnam** [comment]
@oralunal what do you mean? I turned on action in the config file `actionsEnabled: true`, which is shipped with this repo, and the action buttons appear, but not working.

**Comment by oralunal** [comment]
Are you sure about it? Checkout this repo's userdata.js file, there is no actionsEnabled thing

https://github.com/PokemonGoF/PokemonGo-Web/blob/master/config/userdata.js.example
