### ISSUE TITLE
New web readme file doesn't include how to run Web.

### ISSUE THREAD

**Issue by ghost** [PokemonGoF/PokemonGo-Web#30]
I noticed the new readme file doesn't show how to run the web part of the bot. I can't remember it off the top of my head and want to start it. Anyone could help me with the command to get it started on local host?

**Comment by MZorzy** [comment]
on git u can see on "history" of file,
like this
https://github.com/PokemonGoF/PokemonGo-Web/commit/e9322cd8952bcc1bbd70e302d3943d0abe5d3a00

tl.dr
$ cd OpenPoGoBot\web  
$ python -m SimpleHTTPServer

my .2 or don'start simpleserver but point nginx/apache to ./web
