### ISSUE TITLE
Show Level of Pokemons

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Web#32]
Would it be possible to also show the level of the pokemon?

Makes it easier to decide wich one to power-up.

**Comment by Gobberwart** [comment]
What exactly is meant by "level"? Just curious to understand what this means.

**Comment by oralunal** [comment]
Pokemons have a level too like players. You can evolve a pokemon to max 40level(like players).. But their level up is rising 0,5 instead of 1.

25 level charizard, 34,5 level machop etc.

**Comment by oralunal** [comment]
#35
