### ISSUE TITLE
[FR] *.json, db or socket

### ISSUE THREAD

**Issue by rawgni** [PokemonGoF/PokemonGo-Web#36]
PokemonGoF/PokemonGo-Bot#5084

**Comment by oralunal** [comment]
Working on it, we will do it with MQTT..

**Comment by rawgni** [comment]
so , someone is going to implement that on the main bot ?

**Comment by oralunal** [comment]
Yes, @solderzzc and me are working on the MQTT Web UI.

**Comment by MZorzy** [comment]
branch/git ?
