### ISSUE TITLE
Not in Pokedex - Show seen but not caught pokemons

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Web#43]
I try to fill my pokedex and realized that Pokemons that were seen but not caught are not in the "Not in Pokedex" Tab.

**Comment by oralunal** [comment]
So, let's change it's name "Never Caught Pokemons"

**Comment by jane0815** [comment]
Right now the correct name would be "not seen pokemons". 

When a pokemon is seen but not caught it will not be in the list. In Pokedex it will be grey.

**Comment by oralunal** [comment]
@rawgni change it into very nice :)
