### ISSUE TITLE
Just Settings Showing

### ISSUE THREAD

**Issue by BarrieG14** [PokemonGoF/PokemonGo-Web#44]
I am only getting a white screen with a settings cog on the top right hand side when I try running the Web UI under localhost:8000

When I open console I get the following error:

Uncaught ReferenceError: dataUpdates is not defined main.js:166

**Comment by MZorzy** [comment]
missed,error in configuration file maybe

**Comment by BarrieG14** [comment]
My userdata.js is an exact replica of the .example with my username and API key filled in.  The same API key that is working with the -bot.  No errors in there.

**Comment by BarrieG14** [comment]
I ran it in Incognito mode and now working all OK
