### ISSUE TITLE
I have main.js my modify for show power from skill

### ISSUE THREAD

**Issue by poid0010** [PokemonGoF/PokemonGo-Web#47]
![image](https://cloud.githubusercontent.com/assets/20973618/18379301/f6d58298-769b-11e6-898b-70cc148af828.png)
I have main.js my modify for show power from skill 
fastMoves: {
    222: "Pound",
    228: "Metal Claw",
fastMoves**ss**: {
    222: "7",
    228: "12",},
slowMoves: {
    32: "Stone Edge",
    28: "Cross Chop",
slowMoves**ss**: {
    32: "80",
    28: "60",},

<b>Skill: </b> + self.fastMoves[move1ID] + **'[' + self.fastMovesss[move1ID] +** '], ' + self.slowMoves[move2ID] **\+ '[' + self.slowMovesss[move2ID] + ']'** ;

**Comment by demolitionmanza** [comment]
You Modify for mapview ?

**Comment by oralunal** [comment]
This is not an issue, please make this as a PR
