### ISSUE TITLE
Did some modifications on the latest main.js

### ISSUE THREAD

**Issue by mmixx** [PokemonGoF/PokemonGo-Web#48]
![pokemongof-web](https://cloud.githubusercontent.com/assets/2145484/18399082/020621f2-7702-11e6-8b2a-cd47d055ee4f.png)

Modified the layout of Pokemon list and the attack powers of each moves and also added a breakdown of current eggs in your bag. It also show the accumulated distance when hatching eggs using Incubator/s (breakable and unlimited)

**Comment by oralunal** [comment]
Can you make a PR for this, thanks!
