### ISSUE TITLE
howto edit main.js add move power 

### ISSUE THREAD

**Issue by poid0010** [PokemonGoF/PokemonGo-Web#50]
![image](https://cloud.githubusercontent.com/assets/20973618/18407912/8bf48b06-7748-11e6-8d2c-97dd232e8795.png)

slowMoves: {
    32: "Stone Edge",
    28: "Cross Chop",
    83: "Dragon Claw",
    40: "Blizzard",
    131: "Body Slam",
    22: "Megahorn",
    122: "Hurricane",
    116: "Solar Beam",
    103: "Fire Blast",
    14: "Hyper Beam",
    31: "Earthquake",
    118: "Power Whip",
    107: "Hydro Pump",
    117: "Leaf Blade",
    78: "Thunder",
    123: "Brick Break",
    92: "Gunk Shot",
    90: "Sludge Bomb",
    42: "Heat Wave",
    87: "Moonblast",
    91: "Sludge Wave",
    79: "Thunderbolt",
    47: "Petal Blizzard",
    89: "Cross Poison",
    108: "Psychic",
    58: "Aqua Tail",
    24: "Flamethrower",
    88: "Play Rough",
    82: "Dragon Pulse",
    39: "Ice Beam",
    49: "Bug Buzz",
    46: "Drill Run",
    59: "Seed Bomb",
    77: "Thunder Punch",
    100: "X Scissor",
    129: "Hyper Fang",
    64: "Rock Slide",
    94: "Bone Club",
    36: "Flash Cannon",
    74: "Iron Head",
    38: "Drill Peck",
    60: "Psyshock",
    70: "Shadow Ball",
    99: "Signal Beam",
    115: "Fire Punch",
    54: "Submission",
    102: "Flame Burst",
    127: "Stomp",
    35: "Discharge",
    65: "Power Gem",
    106: "Scald",
    109: "Psystrike",
    56: "Low Sweep",
    51: "Night Slash",
    86: "Dazzling Gleam",
    16: "Dark Pulse",
    33: "Ice Punch",
    26: "Dig",
    20: "Vice Grip",
    18: "Sludge",
    96: "Mud Bomb",
    126: "Horn Attack",
    121: "Air Cutter",
    132: "Rest",
    72: "Magnet Bomb",
    57: "Aqua Jet",
    105: "Water Pulse",
    30: "Psybeam",
    63: "Rock Tomb",
    50: "Poison Fang",
    104: "Brine",
    45: "Aerial Ace",
    53: "Bubble Beam",
    95: "Bulldoze",
    125: "Swift",
    62: "Ancient Power",
    114: "Giga Drain",
    69: "Ominous Wind",
    67: "Shadow Punch",
    80: "Twister",
    85: "Draining Kiss",
    21: "Flame Wheel",
    133: "Struggle",
    101: "Flame Charge",
    34: "Heart Stamp",
    75: "Parabolic Charge",
    111: "Icy Wind",
    84: "Disarming Voice",
    13: "Wrap",
    66: "Shadow Sneak",
    48: "Mega Drain"
  },
slowMovess: {
    32: "80",
    28: "60",
    83: "35",
    40: "50",
    131: "70",
    22: "80",
    122: "80",
    116: "120",
    103: "100",
    14: "120",
    31: "100",
    118: "70",
    107: "90",
    117: "55",
    78: "100",
    123: "30",
    92: "65",
    90: "55",
    42: "80",
    87: "85",
    91: "60",
    79: "55",
    47: "65",
    89: "25",
    108: "55",
    58: "45",
    24: "55",
    88: "55",
    82: "65",
    39: "65",
    49: "75",
    46: "50",
    59: "40",
    77: "40",
    100: "35",
    129: "35",
    64: "50",
    94: "25",
    36: "60",
    74: "30",
    38: "40",
    60: "40",
    70: "45",
    99: "45",
    115: "40",
    54: "30",
    102: "30",
    127: "30",
    35: "35",
    65: "40",
    106: "55",
    109: "100",
    56: "30",
    51: "30",
    86: "55",
    16: "45",
    33: "45",
    26: "70",
    20: "25",
    18: "35",
    96: "30",
    126: "25",
    121: "30",
    132: "sleep",
    72: "30",
    57: "25",
    105: "35",
    30: "40",
    63: "30",
    50: "25",
    104: "15",
    45: "30",
    53: "30",
    95: "35",
    125: "30",
    62: "35",
    114: "75",
    69: "30",
    67: "60",
    80: "25",
    85: "25",
    21: "40",
    133: "15",
    101: "25",
    34: "60",
    75: "50",
    111: "25",
    84: "25",
    13: "30",
    66: "40",
    48: "40"
  },
fastMoves: {
    222: "Pound",
    228: "Metal Claw",
    226: "Psycho Cut",
    210: "Wing Attack",
    202: "Bite",
    204: "Dragon Breath",
    220: "Scratch",
    230: "Water Gun",
    240: "Fire Fang",
    213: "Shadow Claw",
    238: "Feint Attack",
    224: "Poison Jab",
    234: "Zen Headbutt",
    239: "Steel Wing",
    201: "Bug Bite",
    218: "Frost Breath",
    233: "Mud Slap",
    216: "Mud Shot",
    221: "Tackle",
    237: "Bubble",
    214: "Vine Whip",
    217: "Ice Shard",
    241: "Rock Smash",
    223: "Cut",
    236: "Poison Sting",
    215: "Razor Leaf",
    212: "Lick",
    206: "Spark",
    203: "Sucker Punch",
    235: "Confusion",
    225: "Acid",
    209: "Ember",
    227: "Rock Throw",
    211: "Peck",
    207: "Low Kick",
    205: "Thunder Shock",
    229: "Bullet Punch",
    219: "Quick Attack",
    200: "Fury Cutter",
    208: "Karate Chop",
    231: "Splash"
  },
fastMovess: {
    222: "7",
    228: "12",
    226: "8",
    210: "9",
    202: "6",
    204: "6",
    220: "6",
    230: "6",
    240: "10",
    213: "11",
    238: "12",
    224: "15",
    234: "12",
    239: "15",
    201: "5",
    218: "9",
    233: "15",
    216: "12",
    221: "12",
    237: "25",
    214: "7",
    217: "15",
    241: "15",
    223: "12",
    236: "6",
    215: "15",
    212: "5",
    206: "7",
    203: "7",
    235: "15",
    225: "10",
    209: "10",
    227: "12",
    211: "10",
    207: "5",
    205: "5",
    229: "10",
    219: "10",
    200: "3",
    208: "6",
    231: "0"
  },
![image](https://cloud.githubusercontent.com/assets/20973618/18407883/db09664a-7747-11e6-9a22-f89ced854ee7.png)

**Comment by demolitionmanza** [comment]
You Flie Modify Main download ?

**Comment by oralunal** [comment]
Please make a PR for this.
