### ISSUE TITLE
Annoying on-screen logs (the black rectangles with text), it is covering half of my screen...

### ISSUE THREAD

**Issue by tohyf** [PokemonGoF/PokemonGo-Web#51]
It seems like it is printing the bot logs on the map, and the logs (in the form of black rectangles overlaying the map) are so plenty that I barely see the map. Can the logs be somehow disabled or hidden away, or adjusted so that the text boxes become smaller?

**Comment by tohyf** [comment]
hmm... looks like it is using materialize css toast ..... 
I made this change to main.css to make the text size and also the box smaller:
#toast-container > .toast {
    float: left;
    font-size: 10px;
    height: 20px;
    min-height:20px;
}
However, sometimes the log will still flood the screen, depending on the events. 
I noticed that there is a "log" feature on the map, why not put the logs into it? it would be much easier to manage and it won't overflow the entire height of screen...

**Comment by mmixx** [comment]
I have sent a PR ( #55 )... I modified the output of the toast that it only show important messages, like when a pokemon apeared or catched... and I also made it a bit smaller...
