### ISSUE TITLE
Unexpected use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by Tych0n** [PokemonGoF/PokemonGo-Web#52]
Got an error in Safari 9.1.3:
![2016-09-11 1 16 58](https://cloud.githubusercontent.com/assets/3283584/18413833/4a0480ec-77c6-11e6-938e-df2c6ec9fd43.png)

such structure isn't supported in safari http://caniuse.com/#search=let

**Comment by oralunal** [comment]
Yes, this is a knows issue, let is not supported by Safari, thanks!
