### ISSUE TITLE
Help in running web view

### ISSUE THREAD

**Issue by jh0s3ph** [PokemonGoF/PokemonGo-Web#57]
I only get directory listing when i type http://192.168.99.100:8000/ using chrome as shown below

"Directory listing for /

catchable-xxxxx@gmail.com.json
config/
configs/
inventory-xxxxxx@gmail.com.json
location-xxxxxx@gmail.com.json"

I did command in docker and have edited the userdata.js

Command in docker as shown below:
docker run --name=bot1-pokegoweb --rm -it --volumes-from bot1-pokego -p 8000:8000 -v $(pwd)/configs/userdata.js:/usr/src/app/web/configs/userdata.js -w /usr/src/app/web python:2.7 python -m SimpleHTTPServer

Edited userdata js as shown below
 // MUST CONFIGURE THE USER ARRAY AND GOOGLE MAPS API KEY.
 // YOU CAN GET A KEY HERE: https://developers.google.com/maps/documentation/javascript/get-api-key
 var userInfo = {
    users: "xxxxx@gmail.com",
    userZoom: false,
    userPath: true,
    zoom: 16,
    userFollow: true,
    gMapsAPIKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 }; 

Docker display as shown below
Serving HTTP on 0.0.0.0 port 8000 ...
192.168.99.1 - - [13/Sep/2016 18:57:53] "GET / HTTP/1.1" 200 -
192.168.99.1 - - [13/Sep/2016 18:57:56] "GET / HTTP/1.1" 200 -
192.168.99.1 - - [13/Sep/2016 18:57:57] "GET / HTTP/1.1" 200 -
192.168.99.1 - - [13/Sep/2016 19:00:24] "GET / HTTP/1.1" 200 -
192.168.99.1 - - [13/Sep/2016 19:00:24] "GET / HTTP/1.1" 200 -
192.168.99.1 - - [13/Sep/2016 19:00:24] code 404, message File not found
192.168.99.1 - - [13/Sep/2016 19:00:24] "GET /favicon.ico HTTP/1.1" 404 -
192.168.99.1 - - [13/Sep/2016 19:01:34] "GET / HTTP/1.1" 200 -

**Comment by rawgni** [comment]
@jh0s3ph you probably want to do `python -m SimpleHTTPServer 8000` if not it will use the default port `80`

**Comment by oralunal** [comment]
It seems pokemongo-web isn't installed. Go to web directory and clone the repo
`git clone https://github.com/PokemonGoF/PokemonGo-Web.git`
