### ISSUE TITLE
The candies are always undefined and general improvements required

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Web#6]
Having the candy counter on the web bot would be one of the best features but sadly it always says undefined. The sorting functions also don't work ( Its always sorted according to the CP ) and there should be an egg tab tracking the eggs or at least the currently incubating eggs distance.

**Comment by proEndreeper** [comment]
Instead of using this repo, use this one: https://github.com/OpenPoGo/OpenPoGoWeb.

Most of the issues you posted are fixed in this one
