### ISSUE TITLE
Error 404 in SimpleHTTPServer - error nickname/account

### ISSUE THREAD

**Issue by ikariya69** [PokemonGoF/PokemonGo-Web#62]
it was working nice until yesterdays updates. Now i get the following errors :

`192.168.1.107 - - [15/Sep/2016 09:12:42] code 404, message File not found
192.168.1.107 - - [15/Sep/2016 09:12:42] "GET /location-Ikariya69.json?1473923562096 HTTP/1.1" 404 -
192.168.1.107 - - [15/Sep/2016 09:12:42] code 404, message File not found
192.168.1.107 - - [15/Sep/2016 09:12:42] "GET /catchable-Ikariya69.json?1473923562097 HTTP/1.1" 404 -
192.168.1.107 - - [15/Sep/2016 09:12:43] code 404, message File not found
192.168.1.107 - - [15/Sep/2016 09:12:43] "GET /location-Ikariya69.json?1473923563084 HTTP/1.1" 404 -
192.168.1.107 - - [15/Sep/2016 09:12:43] code 404, message File not found
192.168.1.107 - - [15/Sep/2016 09:12:43] "GET /catchable-Ikariya69.json?1473923563085 HTTP/1.1" 404 -
192.168.1.107 - - [15/Sep/2016 09:12:44] code 404, message File not found
192.168.1.107 - - [15/Sep/2016 09:12:44] "GET /location-Ikariya69.json?1473923564084 HTTP/1.1" 404 -`

tried to reinstall from beginning the bot multiple times but still getting the error

tried with standard configuraiton files, and with the old ones i had and same issues

got 3.json files in the root web directory :

-rw-r--r--  1 pi pi 124617 sept. 15 09:28 location-xxxxxxxx@gmail.com.json
-rw-r--r--  1 pi pi 106668 sept. 15 09:28 inventory-xxxxxxxx@gmail.com.json
-rw-r--r--  1 pi pi    195 sept. 15 09:28 catchable-xxxxxxx@gmail.com.json

looks like the bot is generating those 3 files with goggle account login whereas webserver looks for the same files but with nickname of the trainer. This nickname isn't specified anywhere in the config files !!

Tried to move the whole config to an old install (that i updated) with a different account, that was working, and the problem appears ! seems to be linked to a recent update in the web master repo

**Comment by JaapMoolenaar** [comment]
Did you configure your "usernames" in /config/userdata.js to include "@gmail.com"?
I'm guessing you should use "Ikariya69@gmail.com".

```
 var userInfo = {
    users: ["Ikariya69@gmail.com"],
    ...
 }; 
```

**Comment by ikariya69** [comment]
no, in the userdarta.js i put my real google email linked to pokemonGO account, and witch  nickname in the game is Ikariya69

this nickname is no written anywhere in the config files

**Comment by JaapMoolenaar** [comment]
What the script basically does is iterate through the users configured in userdata.js. Every iteration it tries to retrieve `location-<username-from-userdata.js>.json`.

So, somewhere, somehow, the script is (still) using `Ikariya69` as a user name, and thus tries to retrieve `location-Ikariya69.json`.

**Comment by ikariya69** [comment]
thats what im thinking but can't find where 
none of my config files includes this nickname

**Comment by JaapMoolenaar** [comment]
It doesn't have to. There could still be a browser or tab or something open, using old config files. Maybe not your browser even, maybe sombody else's?

Point is, I don't think it's yesterday's updates ;-)

**Comment by ikariya69** [comment]
i must be totally mad, or my Pi is joking me ...
or maybe the sftp transfert
i changed this settings in userdata.js then uploaded the file with sftp but there should have be a problem because the user data on the Pi was still with the nickname :s i checked however multiple times :s
sorry to have bothered you with this !
