### ISSUE TITLE
sidebar with names.

### ISSUE THREAD

**Issue by Asphyriax** [PokemonGoF/PokemonGo-Web#7]
when i open the submenu from the bottom names i cant see them,

like this.

so if you can make a scrollbar, i have tried but failed.

![sidebar 00](https://cloud.githubusercontent.com/assets/10586816/17367387/fac53eb2-598f-11e6-8ede-6a7c8ce8fd30.PNG)
![sidebar01](https://cloud.githubusercontent.com/assets/10586816/17367388/fadd8382-598f-11e6-955b-f1d8549a4d25.PNG)
![sidebar02](https://cloud.githubusercontent.com/assets/10586816/17367389/fb0be93e-598f-11e6-8a85-74c81077bcbc.PNG)

**Comment by ProjectBarks** [comment]
We are working on a better UI to fix this problem
