### ISSUE TITLE
SyntaxError: Unexpected token '>'

### ISSUE THREAD

**Issue by janpascal** [PokemonGoF/PokemonGo-Web#70]
Hi all,

Just update the web submodule in pokemongo-bot to the latest master and also updated my `config/userdata.js`. I'm running a python SimpleHTTPServer. When I connect using Safari on MacOS X, I get a javascript error:
`SyntaxError: Unexpected token '>'` in util.js (line 4).

That line reads:
`xhr.onreadystatechange = _ => {`

That line looks quirky to me, maybe it's some new fashioned JavaScript syntax I don't know about?

The result is that the web interface doesn't show any users. 

What can I do to fix this?

Thanks for any help

Jan-Pascal

**Comment by rawgni** [comment]
@janpascal change it to `_ =>` to `function ()`. It's ES6 Arrow Function.

**Comment by janpascal** [comment]
Should we do that for every occurrence of that construct (if there are more)? I can check and prepare a PR

On 21 September 2016 16:19:41 CEST, Ingwar Wirjawan notifications@github.com wrote:

> @janpascal change it to `_ =>` to `function ()`
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/PokemonGoF/PokemonGo-Web/issues/70#issuecomment-248626574

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by goedzo** [comment]
Fixed.
