### ISSUE TITLE
How to access websocket using Docker ?

### ISSUE THREAD

**Issue by lokiiiii** [PokemonGoF/PokemonGo-Web#78]
Hi there,

I've browsed the issues but didn't find one that could help:

It's been a few weeks now that I'm trying to enable the websocket connexion between Web & Bot.

I use Docker with the last "master" commit and I'm using the docker-compose.yml of PokemonGoF/PokemonGo-Bot to start the webserver, the websocket and the bot.

I think that my websocket is well configured but when I access the Web map, I can see my trainer doing its stuff, but the logs won't work (it never did) and since the last commit, I now have an error message saying that it can't access "0.0.0.0:4000" and that it will try again in 30s.

When checking my server, a netstat command shows me that my port 4000 is actually listening right now.

Is there a way to be sure that my websocket is actually listening and doing things ?

My config.json contains:

```
"websocket_server": true,
and
"websocket": { "start_embedded_server": true, "server_url": "0.0.0.0:4000" }
```

If someone could help, it would be awesome :)
Thanks all !

**Comment by mmixx** [comment]
I haven't used Docker since... but can you try to change the IP it's listening to? Instead of 0.0.0.0, use 127.0.0.1... both on the bot's config.json and web's userdata.js...

**Comment by ricardofiorani** [comment]
If your trainer is moving then the socket is working right ? I mean, does the logs shows something other than "trainer loaded" ?

**Comment by mmixx** [comment]
Nope... If your trainer is moving, it's because of this line:

```
        loadJSON('location-' + self.settings.users[i].username + '.json?'+Date.now(), self.trainerFunc, self.errorFunc, i);
```

It gets the current location of the trainer/s that is being saved by the bot to a .json file that is accessed by the web.

**Comment by lokiiiii** [comment]
@mmixx I tried to change 0.0.0.0 to 127.0.0.1, but it remains the same : web server can't connect to web socket.

@ricardofiorani As @mmixx said, The trainer moving is related the web server catching the .json files under my server, and THAT works, no issue, with that.

When I access the web server, all I got is:
- loading data
- data loaded
- trainer loaded
- and then I got the connexion error towards the web socket

I tried to change the web socket adress under userdata.js to specify:
- the IP of my web socket container : FAIL
- the IP of my bot container : FAIL
- the IP of my server : FAIL

When I try to debug using the development tools of my browser, I can see that the web server is reading my .json files, so no issue at all with the menus, the pokemons, the items or the trainer, It's just the web socket part that should show bot actions that won't work.

Thanks anyway for your help, greatly appreciated :)

**Comment by ricardofiorani** [comment]
Are you using Docker-Compose or running each container by hand ? 
If using docker-compose, have you changed something on the `docker-compose.yml` ?
Also, have you checked if is there another service running on port 4000 before you get the bot/ws up ?
Are you using windows or linux ?

**Comment by lokiiiii** [comment]
@ricardofiorani Yes, I'm using docker-compose to run my 3 containers (bot + web + socket)
I didn't change anything in this docker-compose.yml, except the port declared under the web server (my 8000 is already used by my webserver - nginx - so I modified ports: "8000:8000" to ports: "8080:8000" but I don't think that it could cause some issues)

And I've done some netstat commands before & after starting the bot, everything looks fine:
When the bot is not started, port 4000 isn't declared under netstat but it IS listening as soon as my web server is started by docker-compose.

And i'm under Debian 8 :)

**Comment by ricardofiorani** [comment]
Have you tried putting your own machine's IP from your LAN on your `userdata.js` ?

**Comment by lokiiiii** [comment]
As I already said before (this is not mean, I've put so much infos you may not have seen that one :p ), I've already tried many different configurations:

I tried to change the web socket adress under userdata.js to specify:
- the IP of my web socket container : FAIL
- the IP of my bot container : FAIL
- the IP of my server (the main IP ^^) : FAIL

PS: I'm not english, so sorry in advance for my bad words / sentences... :p

**Comment by ricardofiorani** [comment]
could you provide your `docker-compose.yml` and `Dockerfile` ?

**Comment by lokiiiii** [comment]
The docker-compose is the same as the "master branch repository" except I've put "ports : "8080:8000" instead of "8000:8000" under the web server configuration.
And I didn't change a thing under the Dockerfile file (maybe "dev" instead of "master" under branch info but it shouldn't be an issue ^^)

Do you need any more info ?

**Comment by mmixx** [comment]
Can you change the ports you set to "8000:8080"?

**Comment by lokiiiii** [comment]
Well, the first port is the one used on my server and the second one is the one used by the web server container: If I change it as you suggested, I won't access my web server anymore, and my container won't start anyway as I already have nginx (webserver) which is running on 8000

PS: I don't understand as my web server container IS working, only the websocket connexion isn't

Thanks anyway :)

**Comment by mmixx** [comment]
Oh... Sorry, haven't used docker so I didn't know that...

**Comment by lokiiiii** [comment]
No problem, thank you for trying to help me :)

**Comment by goedzo** [comment]
Old issue. UI works fine now. Closing issue.
