### ISSUE TITLE
[Feature] Sending command from Web to Bot

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Web#8]
Do you think it would be possible to control the bot from the Web page?
I was taking a look at how bot writes out to web's json files, and though: could it also **read** json data? This could lead to changing configs on the fly (maybe?), possibility of taking actions like evolving/releasing/fav-ing a pokemon, managing both pokemon and item bags.
Maybe also changing path/location could be possible..

What about writing a queue of commands out to a json file, and let the bot read that file at some time or along with some action it takes?
It would be necessary to have a strict control on those input commands, but I don't see any reason why this couldn't be realized. What do you think?

**Comment by iruy** [comment]
Lol, I found out that there is something like this already, set up on a socket. Anybody knows where the bot is listening? Which file?
[Evolve / Release](https://cloud.githubusercontent.com/assets/8875681/17422495/ebc5180a-5ab2-11e6-9ace-858bb2be47c5.png)

**Comment by ProjectBarks** [comment]
We have a websocket setup through the core bot. Take a look there. We have plans of implementing this in future versions. For now I am going to close this since it is up and coming.
