### ISSUE TITLE
Still can't run web view. Using docker for bot

### ISSUE THREAD

**Issue by jh0s3ph** [PokemonGoF/PokemonGo-Web#91]
Made fresh copy of everything. bot is running okay but web view still don't want to work.

Docker window shows the following when i try to execute the command instructed in https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/installation.md

---

xxxxx@xxxxxx MINGW64 ~/pokemongo-bot/web (master)
$ docker run --name=bot1-pokegoweb --rm -it --volumes-from bot1-pokego -p 8000:
8000 -v $(pwd)/configs/userdata.js:/usr/src/app/web/config/userdata.js -w /usr/
src/app/web python:2.7 python -m SimpleHTTPServer
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/a332a3749d6a7823ed79c852eecf7bb1429692b51b4609e170ffa1f91b51d607/usr/src/app/web/config/userdata.js" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/a332a3749d6a7823ed79c852eecf7bb1429692b51b4609e170ffa1f91b51d607" caused "not a directory".

xxxxx@xxxxxx MINGW64 ~/pokemongo-bot/web (master)
$ cd ..

xxxxx@xxxxxx MINGW64 ~/pokemongo-bot (master)
$ docker run --name=bot1-pokegoweb --rm -it --volumes-from bot1-pokego -p 8000:
8000 -v $(pwd)/configs/userdata.js:/usr/src/app/web/config/userdata.js -w /usr/
src/app/web python:2.7 python -m SimpleHTTPServer
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/333f76744dfbe8b27ff60c3a4ad9aa4d8a6d465428c40930d459a6e0a30a4ac2/usr/src/app/web/config/userdata.js" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/333f76744dfbe8b27ff60c3a4ad9aa4d8a6d465428c40930d459a6e0a30a4ac2" caused "not a directory".

---

config.js as follows:

 // MUST CONFIGURE THE USER ARRAY AND GOOGLE MAPS API KEY.
 // YOU CAN GET A KEY HERE: https://developers.google.com/maps/documentation/javascript/get-api-key
 var userInfo = {
    users: [{
            enable: true,
        username: "should_i_put_my_pokego_username_or_my_gmail_here??",
        socketAddress: "0.0.0.0:4000",
        enableSocket: true
    },{
            enable: false,
        username: "username2",
        socketAddress: "0.0.0.0:5000",
        enableSocket: false
    }],
    userZoom: false,
    userPath: true,
    zoom: 16,
    userFollow: true,
    gMapsAPIKey: "xxxxxxxxxx"
 };

![1](https://cloud.githubusercontent.com/assets/22131182/19119357/18e9a57e-8b52-11e6-9ece-ecc9718aa54f.jpg)

**Comment by mmixx** [comment]
Don't know if there's a problem using web socket on docker... But I've seen a lot online (while searching a solution on google) that has a problem with it...

**Comment by goedzo** [comment]
Old issue. UI works fine now. Closing issue.
