### ISSUE TITLE
web UI is not working

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Web#94]
when going to the webiu page only a settings button is showing. bot and map is not loaded

inventory-XXX.json and location-XXXX.json is updated in the web folder as expected

**Comment by mmixx** [comment]
Have you setup your `config/userdata.js` on your bot's web directory?

**Comment by beltoft** [comment]
yes or else the inventory-XXX.json and location-XXXX.json files wouldn't be updated when bot is running right?

**Comment by DRiNVAD3R** [comment]
Have you started the web service?
You need to run 
`./web.sh`
then everything should work if you have edited the configs correctly

**Comment by beltoft** [comment]
I'm running a nginx Web server and it's pointing to the right folder and is running.
If not then the settings button would not be loaded as described in the first post

**Comment by goedzo** [comment]
Old issue. UI works fine now. Closing issue.
