### ISSUE TITLE
Remote Connection failed

### ISSUE THREAD

**Issue by DRiNVAD3R** [PokemonGoF/PokemonGo-Web#96]
When accessing on web on the host machine everything works, but once I access remotely (via ip in same network) I keep getting the Error: 
`Connecting to 'http://127.0.0.1:4000' failed. Retrying after 30 seconds.`

It says before:

```
Loading Data..
Data Loaded!
Trainer Loaded: XXX
```

EDIT: Trainer Data works fine, shows Pokémon and Items but the Location seems to be bugged

**Comment by cierzniak** [comment]
Same here in WebUI i see log:

```
12:47
Reconnecting to http://127.0.0.1:4002...
12:47
Reconnecting to http://127.0.0.1:4001...
12:47
Reconnecting to http://127.0.0.1:4000...
12:47
Connecting to 'http://127.0.0.1:4002' failed. Retrying after 30 seconds.
12:47
Connecting to 'http://127.0.0.1:4001' failed. Retrying after 30 seconds.
12:47
Connecting to 'http://127.0.0.1:4000' failed. Retrying after 30 seconds.
12:46
Trainer loaded: xxx3
12:46
Trainer loaded: xxx2
12:46
Trainer loaded: xxx1
12:46
Data Loaded!
12:46
Loading Data..
```

**Comment by DRiNVAD3R** [comment]
Ok I found the mistake. Following files have to be changed:
- **/configs/config.json**
  `
  "websocket": {
      "start_embedded_server": true,
      "server_url": "127.0.0.1:4000"
  }
  `
  to
  `
  "websocket": {
      "start_embedded_server": true,
      "server_url": "XXX.XXX.XXX.XXX:4000"
  }
  `
- **/web/config/userdata.js** 
  `socketAddress: "127.0.0.1:4000"`
  to
  `socketAddress: "XXX.XXX.XXX.XXX:4000"`

where XXX.XXX.XXX.XXX is your host machines IP address so for example _192.168.178.26:4000_

After changing this I can remotely access the Web GUI and everything works as it should.
